# based on template here: https://github.com/marketplace/actions/python-poetry-action
name: CI
on: [push]
jobs:
  ci:
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]
        poetry-version: [1.1.4]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Poetry (Dependency Manager)
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Run Checks
        run: "make check"
